name: Pack and Push to GPR

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack -c Release --no-restore --no-build --verbosity normal

    #- name: Add private feed
    #  run: dotnet nuget add source https://nuget.pkg.github.com/iotmodels/index.json -n GPR -u iotmodels -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    # using curl from https://github.com/NuGet/Home/issues/8580#issuecomment-555696372
    - name: push
      run: |
        for f in dtdl2-validator/bin/Release/*.nupkg
        do
             curl -vX PUT -u "ridomin:${{ secrets.GHPackagesToken }}" -F package=@$f https://nuget.pkg.github.com/iotmodels/
        done
      shell: bash
