name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --no-restore --verbosity normal

    - name: Add private feed
      run: dotnet nuget add source https://nuget.pkg.github.com/iotmodels/index.json -n GPR -u iotmodels -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: push
      run: |
        for f in dtdl2-validator/bin/Release/*.nupkg
        do
            dotnet nuget push $f --source "GPR" 
        done
      shell: bash
